import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const items = [
//   {
//     text: "Accueil",
//     lucide: <Home />,
//     link: "/",
//   },
//   {
//     text: "J'adopte",
//     lucide: <Dog />,
//     link: "/volunteersView/searchPet",
//   },
//   {
//     text: "Je deviens bénévole",
//     lucide: <PersonStanding />,
//     link: "/volunteersView/beVolunteer",
//   },
//   {
//     text: "Je donne",
//     lucide: <Handshake />,
//     link: "/volunteersView/donation",
//   },
//   {
//     text: "Je me connecte",
//     lucide: <LogIn />,
//     link: "/SignIn",
//   },
// ];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Footer/>
      </body>
    </html>
  );
}
